### ISSUE TITLE
Error when using grapplinghook with left hand

### ISSUE THREAD

**Issue by GHsorryiwon12345** [lucian929/GrapplingHook#2]
git-Airplane-"ec7d3d0" (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT)

[00:43:50] [Server thread/ERROR]: Could not pass event PlayerFishEvent to GrapplingHook v1.9
java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.meta.ItemMeta.getItemFlags()" because the return value of "org.bukkit.inventory.ItemStack.getItemMeta()" is null
	at net.maploop.GrapplingHook.onRightClick(GrapplingHook.java:54) ~[GrapplingHook-1.9.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor47.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Airplane-"ec7d3d0"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.17.1.jar:git-Airplane-"ec7d3d0"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Airplane-"ec7d3d0"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.1.jar:git-Airplane-"ec7d3d0"]
	at net.minecraft.world.entity.projectile.EntityFishingHook.a(EntityFishingHook.java:554) ~[patched_1.17.1.jar:git-Airplane-"ec7d3d0"]
	at net.minecraft.world.item.ItemFishingRod.a(ItemFishingRod.java:30) ~[patched_1.17.1.jar:git-Airplane-"ec7d3d0"]
	at net.minecraft.world.item.ItemStack.a(ItemStack.java:473) ~[patched_1.17.1.jar:git-Airplane-"ec7d3d0"]
	at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:492) ~[patched_1.17.1.jar:git-Airplane-"ec7d3d0"]
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1874) ~[patched_1.17.1.jar:git-Airplane-"ec7d3d0"]
	at net.minecraft.network.protocol.game.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:28) ~[patched_1.17.1.jar:git-Airplane-"ec7d3d0"]
	at net.minecraft.network.protocol.game.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:8) ~[patched_1.17.1.jar:git-Airplane-"ec7d3d0"]
	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56) ~[patched_1.17.1.jar:git-Airplane-"ec7d3d0"]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Airplane-"ec7d3d0"]
	at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149) ~[patched_1.17.1.jar:git-Airplane-"ec7d3d0"]
	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23) ~[patched_1.17.1.jar:git-Airplane-"ec7d3d0"]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1407) ~[patched_1.17.1.jar:git-Airplane-"ec7d3d0"]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:190) ~[patched_1.17.1.jar:git-Airplane-"ec7d3d0"]
	at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122) ~[patched_1.17.1.jar:git-Airplane-"ec7d3d0"]
	at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1385) ~[patched_1.17.1.jar:git-Airplane-"ec7d3d0"]
	at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1378) ~[patched_1.17.1.jar:git-Airplane-"ec7d3d0"]
	at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132) ~[patched_1.17.1.jar:git-Airplane-"ec7d3d0"]
	at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1354) ~[patched_1.17.1.jar:git-Airplane-"ec7d3d0"]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1265) ~[patched_1.17.1.jar:git-Airplane-"ec7d3d0"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[patched_1.17.1.jar:git-Airplane-"ec7d3d0"]
	at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by lucian929** [comment]
Fixed
